apiVersion: skaffold/v2beta5
kind: Config
profiles:
- name: circleci
  build:
    tagPolicy:
      envTemplate:
        template: "{{.IMAGE_NAME}}:{{.CIRCLE_BRANCH}}-{{.CIRCLE_SHA1}}"
    artifacts:
    - image: asia.gcr.io/selfkey2/selfkey-web
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NODE_ENV: production
    local:
      push: true
- name: dev
  build:
    local:
      push: false
    artifacts:
    - image: selfkey-web
      context: .
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          NODE_ENV: development
      sync:
        infer:
        - "**/*"
  activation:
    - command: dev
  deploy:
    kubeContext: docker-desktop
    helm:
      releases:
        - name: selfkey-web
          chartPath: ./charts/selfkey-web
          remote: false
          artifactOverrides:
            image: selfkey-web
          overrides:
            service:
              type: NodePort
              port: 3000
- name: run
  build:
    local:
      push: false
    artifacts:
    - image: asia.gcr.io/selfkey2/selfkey-web
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NODE_ENV: production
  activation:
    - command: run
    - command: delete
  deploy:
    kubeContext: docker-desktop
    helm:
      releases:
        - name: selfkey-web-local-prod
          chartPath: ./charts/selfkey-web
          remote: false
          artifactOverrides:
            image: asia.gcr.io/selfkey2/selfkey-web
          overrides:
            service:
              type: NodePort
              port: 3000